const text = [
  `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
  `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
  `Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
  `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
  `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
  `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
  `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
  `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
  `I'm baby readymade cloud bread scenester kale chips, etsy put a bird on it mlkshk selfies pop-up VHS tumblr hammock drinking vinegar leggings four dollar toast. Lumbersexual tattooed letterpress meggings bitters, ugh subway tile etsy XOXO shabby chic franzen marxism grailed pork belly kickstarter. Copper mug mlkshk kitsch affogato roof party leggings, adaptogen umami la croix gochujang pop-up blog mukbang scenester. Pabst bespoke lumbersexual disrupt.`,
  `Ennui umami artisan everyday carry. Blog ugh hot chicken messenger bag health goth, post-ironic disrupt ascot tumeric food truck crucifix portland hoodie succulents. Heirloom vexillologist ethical schlitz, fixie scenester pinterest fit keytar tumeric. Direct trade readymade roof party, pop-up kinfolk lumbersexual viral 90's gentrify stumptown knausgaard. Twee typewriter wayfarers waistcoat. Lo-fi selfies mukbang, hashtag leggings hella flexitarian. Vice cray beard normcore cardigan locavore artisan vibecession ugh humblebrag shaman food truck microdosing pickled 3 wolf moon.`,
  `Tonx dreamcatcher enamel pin wolf marfa. Fanny pack poke leggings pickled raclette pabst. Helvetica banjo deep v bruh gastropub celiac godard big mood. Kogi snackwave vexillologist, chillwave hashtag etsy blackbird spyplane fashion axe bruh roof party pork belly literally sus cardigan. Wayfarers truffaut tilde, iceland polaroid salvia cliche slow-carb. Coloring book big mood raw denim bushwick vibecession franzen bodega boys hella.`,
  `Art party unicorn cold-pressed austin skateboard biodiesel live-edge single-origin coffee health goth marfa Brooklyn gentrify taiyaki. Organic big mood humblebrag, truffaut whatever XOXO letterpress vexillologist fashion axe JOMO street art. Lo-fi pork belly bushwick, kombucha keytar fanny pack occupy thundercats bitters coloring book ethical authentic shoreditch adaptogen hammock. Glossier franzen raw denim XOXO semiotics before they sold out keytar swag deep v next level. Umami roof party tofu bitters flexitarian cloud bread chartreuse iceland. Flexitarian sriracha blackbird spyplane dreamcatcher.`,
  `Letterpress blog photo booth man bun, iPhone bushwick listicle. Man bun tofu vexillologist prism, solarpunk slow-carb bodega boys vape kinfolk tonx venmo. Deep v small batch celiac meggings kale chips blue bottle trust fund williamsburg swag roof party praxis. PBR&B chartreuse typewriter, yuccie lumbersexual next level unicorn chia 3 wolf moon. Pork belly craft beer ugh blackbird spyplane, quinoa tumeric chia four loko disrupt portland pop-up praxis copper mug DSA XOXO.`,
]
export default text
